name: remote ssh command
on: [push]

jobs:

  build-on-vm:
    name: build-on-vm
    runs-on: ubuntu-latest
    steps:

    - name: executing remote ssh commands using password
      uses: ./
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script:: |
          docker ps
          ls -al
